language: java

jdk:
  - oraclejdk8

branches:
  only:
    - master

before_script:
  - mkdir testData/spill_out
  - chmod ugo+x run-test.sh
script:
  - mvn assembly:assembly
  - cp target/PMT-MapReduce-1.0-SNAPSHOT-jar-with-dependencies.jar mapreduce.jar
  - java -jar mapreduce.jar
  - ./run-test.sh