language: java

jdk:
  - oraclejdk8

branches:
  only:
    - master

before_script:
  - su mkdir /root/spill_out
  - su cp testData/input.txt /root/input.txt
  - su chmod ugo+x run-test.sh
script:
  - mvn assembly:assembly
  - mv target/PMT-MapReduce-1.0-SNAPSHOT-jar-with-dependencies.jar /root/mapreduce.jar
  - java -jar /root/mapreduce
  - ./run-test.sh