language: java

jdk:
  - oraclejdk8

branches:
  only:
    - master

before_script:
  - sudo mkdir /root/spill_out
  - sudo cp testData/input.txt /root/input.txt
  - sudo chmod ugo+x run-test.sh
script:
  - mvn assembly:assembly
  - sudo jdk_switcher use oraclejdk8
  - sudo java -jar target/PMT-MapReduce-1.0-SNAPSHOT-jar-with-dependencies.jar
  - ./run-test.sh